# Pre-commit hooks for code quality and formatting
# See https://pre-commit.com for more information

default_language_version:
  python: python3.11

repos:
  # Remove trailing whitespace, fix end of files, check yaml/json syntax
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
        description: This hook trims trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of files
        description: Ensures that a file is either empty, or ends with one newline
      - id: check-yaml
        name: Check YAML
        description: This hook checks yaml files for parseable syntax
      - id: check-json
        name: Check JSON
        description: This hook checks json files for parseable syntax
      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=1000']
        description: Prevent giant files from being committed
      - id: check-merge-conflict
        name: Check for merge conflicts
        description: Check for files that contain merge conflict strings
      - id: check-docstring-first
        name: Check docstring is first
        description: Checks a common error of defining a docstring after code
      - id: debug-statements
        name: Debug statements (Python)
        description: Check for debugger imports and py37+ `breakpoint()` calls
      - id: mixed-line-ending
        name: Mixed line ending
        args: ['--fix=lf']
        description: Checks for mixed line ending

  # isort - Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: Sort imports with isort
        args: [
          '--profile', 'black',
          '--line-length', '100',
          '--multi-line', '3',
          '--trailing-comma',
          '--force-grid-wrap', '0',
          '--use-parentheses',
          '--ensure-newline-before-comments'
        ]
        description: Sort Python imports

  # black - Python code formatter
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        name: Format code with black
        args: ['--line-length', '100']
        language_version: python3.11
        description: Uncompromising Python code formatter

  # flake8 - Python linter
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: Lint with flake8
        args: [
          '--max-line-length', '100',
          '--extend-ignore', 'E203,W503,E501',
          '--max-complexity', '10'
        ]
        additional_dependencies: [
          'flake8-bugbear>=24.2.6',
          'flake8-comprehensions>=3.14.0',
          'flake8-simplify>=0.21.0',
          'flake8-docstrings>=1.7.0',
          'pep8-naming>=0.13.3'
        ]
        description: Python linter with plugins

  # mypy - Static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        name: Type check with mypy
        args: [
          '--ignore-missing-imports',
          '--no-implicit-optional',
          '--warn-redundant-casts',
          '--warn-unused-ignores'
        ]
        additional_dependencies: [
          'types-requests',
          'types-PyYAML',
          'types-python-dateutil'
        ]
        description: Static type checker for Python

  # ruff - Fast Python linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
        name: Lint with ruff
        args: [
          '--line-length', '100',
          '--fix',
          '--exit-non-zero-on-fix'
        ]
        description: Fast Python linter

  # bandit - Security linter
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        name: Security check with bandit
        args: ['-r', 'cogniforge', '--skip', 'B101']
        description: Find common security issues in Python

  # prettier - Format non-Python files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: Format with prettier
        types_or: [yaml, json, markdown]
        args: ['--print-width', '100']
        description: Format YAML, JSON, and Markdown files